spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demo
    username: test
    password: test
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml